[project]
name = "pyscripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flagembedding==1.3.5",
    "onnx==1.20.1",
    "onnxscript==0.5.7",
    "transformers==4.57.3",
]
