name: "CI"
on:
  merge_group:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  RUSTFLAGS: "-C target-feature=+aes,+sse2"

jobs:
  Rust-checks:
    name: rust checks
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v6

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: cargo build
        run: |
          cd backend 
          cargo build --all-targets --all-features

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Rustfmt Check
        run: |
          cd backend  
          cargo fmt --all --check

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - name: Clippy Check
        run: |
          cd backend
          cargo clippy --workspace --all-targets -- -Dwarnings

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Cargo test
        run: |
          cd backend
          cargo nextest run --workspace --all-targets --all-features --no-tests=pass
